kubectl apply -f database/k8s/mysql-pvc.yml
kubectl apply -f database/k8s/mysql-deployment.yml
kubectl apply -f tools/k8s/mysql-exporter-configmap.yml
kubectl apply -f tools/k8s/mysql-exporter-deployment.yml
kubectl apply -f tools/k8s/prometheus-config.yml
kubectl apply -f tools/k8s/prometheus-deployment.yml
kubectl apply -f tools/k8s/grafana-deployment.yml
kubectl apply -f WBAM-Back/k8s/backend-deployment.yml
kubectl apply -f wbam-front-buildv7/k8s/frontend-deployment.yml
