FROM nginx:alpine

COPY ./wbam-front-buildv7 /usr/share/nginx/html

# Copy the custom Nginx configuration file to replace the default configuration
COPY ./nginx-custom-frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
