server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://loki-container:3100/loki/api/v1/push"

scrape_configs:
  - job_name: "docker-logs"
    
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"
      - source_labels: ["__meta_docker_image"]
        target_label: "image"
      - source_labels: ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - replacement: "docker-logs"  
        target_label: "job"
