{
 "title": "Testboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Container Status",
   "type": "stat",
   "description": "Shows if container is running and when last seen. ",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    time() - container_last_seen{container_label_com_docker_compose_service=~\"frontend|grafana|backend|mysql-exporter|mysql|prometheus|cadvisor\"},\r\n    \"name\",\r\n    \"$1\",\r\n    \"container_label_com_docker_compose_service\",\r\n    \"(.*)\"\r\n  )\r\n) by (name)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage % by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    clamp_max(\r\n      irate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"frontend|grafana|backend|mysql|prometheus|cadvisor|mysql-exporter\"}[30s]) * 100, \r\n      100\r\n    )\r\n    * on (id) group_left()\r\n    clamp_max((time() - container_last_seen{container_label_com_docker_compose_service=~\"frontend|grafana|backend|mysql|prometheus|cadvisor|mysql-exporter\"} <= 30), 1),\r\n    \"name\",\r\n    \"$1\",\r\n    \"container_label_com_docker_compose_service\",\r\n    \"(.*)\"\r\n  )\r\n) by (name)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB) by Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    (container_memory_usage_bytes{container_label_com_docker_compose_service=~\"frontend|grafana|backend|mysql|prometheus|cadvisor|mysql-exporter\"} / (1024 * 1024)),\r\n    \"name\",\r\n    \"$1\",\r\n    \"container_label_com_docker_compose_service\",\r\n    \"(.*)\"\r\n  )\r\n  * on (name) group_left()\r\n  sum(\r\n    label_replace(\r\n      clamp_max((time() - container_last_seen{container_label_com_docker_compose_service=~\"frontend|grafana|backend|mysql|prometheus|cadvisor|mysql-exporter\"}) <= 30, 1),\r\n      \"name\",\r\n      \"$1\",\r\n      \"container_label_com_docker_compose_service\",\r\n      \"(.*)\"\r\n    )\r\n  ) by (name)\r\n) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}