{
 "title": "MYSQL-Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,12h,1d,2d" }
  ]
 },
 "panels": [
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$database\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$database\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$database\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$database\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects{instance=\"$database\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$database\"}[5m])",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$database\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$database\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$database\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$database\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Database Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$database\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$database\"}[5m])"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "stat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$database\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$database\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  }
 ]
}