name: Validate Kubernetes Manifests

on:
  push:
    branches:
      - main
      - ci-cd-pipeline

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install kubeval
        run: |
          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin/

      -      - name: Validate Kubernetes YAML files
      run: |
        find k8s/ -name '*.yaml' -exec kubeval {} \;
    